package com.miozira

import android.Manifest
import android.content.pm.PackageManager
import android.os.ParcelFileDescriptor
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.miozira.core.model.InteractionId
import com.miozira.core.model.SessionId
import com.miozira.core.result.AppResult
import com.miozira.services.microphone.AndroidSpeechAttemptDetector
import com.miozira.services.microphone.MicrophoneError
import com.miozira.services.microphone.SpeechAttemptHandle
import com.miozira.services.microphone.SpeechAttemptListener
import com.miozira.services.microphone.SpeechAttemptRequest
import java.io.File
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicInteger
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertTrue
import kotlinx.coroutines.runBlocking
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class ChildAudioPrivacyTest {
    @Test
    fun shortChildAttemptCapture_createsNoFiles() = runBlocking {
        val instrumentation = InstrumentationRegistry.getInstrumentation()
        val context = instrumentation.targetContext
        val grantCommand = instrumentation.uiAutomation.executeShellCommand(
            "pm grant ${context.packageName} ${Manifest.permission.RECORD_AUDIO}",
        )
        ParcelFileDescriptor.AutoCloseInputStream(grantCommand).use { stream -> stream.readBytes() }
        assertEquals(
            PackageManager.PERMISSION_GRANTED,
            context.checkSelfPermission(Manifest.permission.RECORD_AUDIO),
        )
        val before = childStorageSnapshot(context.filesDir) + childStorageSnapshot(context.cacheDir)
        val terminal = CountDownLatch(1)
        val terminalCount = AtomicInteger(0)
        val detector = AndroidSpeechAttemptDetector(context)

        try {
            val result = detector.start(
                SpeechAttemptRequest(
                    sessionId = SessionId("privacy-session"),
                    interactionId = InteractionId("privacy-interaction"),
                    durationMs = 300,
                ),
                listener = object : SpeechAttemptListener {
                    override fun onAttemptDetected(handle: SpeechAttemptHandle) {
                        terminalCount.incrementAndGet()
                        terminal.countDown()
                    }

                    override fun onNoAttemptDetected(handle: SpeechAttemptHandle) {
                        terminalCount.incrementAndGet()
                        terminal.countDown()
                    }

                    override fun onMicrophoneUnavailable(error: MicrophoneError) {
                        terminalCount.incrementAndGet()
                        terminal.countDown()
                    }
                },
            )

            assertIs<AppResult.Success<SpeechAttemptHandle>>(result)
            assertTrue(terminal.await(3, TimeUnit.SECONDS), "capture did not reach a terminal event")
            assertEquals(1, terminalCount.get())
            val after = childStorageSnapshot(context.filesDir) + childStorageSnapshot(context.cacheDir)
            assertEquals(before, after)
        } finally {
            detector.stopAll()
        }
    }

    private fun childStorageSnapshot(root: File): Set<String> = root.walkTopDown()
        .filter(File::isFile)
        .map { it.relativeTo(root).path }
        // AndroidX ProfileInstaller asynchronously creates this app-startup marker. It is not
        // generated by microphone capture and may appear after the test's initial snapshot.
        .filterNot { it == "profileInstalled" }
        .toSet()
}
